name: deepsort-gpu

dependencies:
  - python==3.7
  - pip
  - matplotlib
  - opencv
  - cudnn
  - cudatoolkit==10.1.243
  - pip:
    - tensorflow-gpu==2.3
    - lxml
    - tqdm
    - seaborn
    - pillow
    - imutils 
    - tensorflow-probability
